### ISSUE TITLE
android-weekly

### ISSUE THREAD

**Issue by BrotherJing** [dyweb/android-stuff#1]
## data binding系列

https://blog.stylingandroid.com/data-binding-part-1/
## annotation基础知识

https://medium.com/sebs-top-tips/annotations-to-support-your-contracts-609ff259d5df
## android中的MVVM

https://medium.com/ribot-labs/approaching-android-with-mvvm-8ceec02d5442
## MVP

https://github.com/rallat/EffectiveAndroid
## android wifi adb

run and debug your app without USB connection
https://github.com/pedrovgs/AndroidWiFiADB
## android ci

https://app.greenhouseci.com

**Comment by at15** [comment]
www @arrowrowe

**Comment by arrowrowe** [comment]
麻烦 @BrotherJing 提供:
- 安卓组周报发送地址 (随便取一个... 比如  `android-weekly@dongyue.io`)
- 安卓组成员共用的接收地址 (比如 `android-members@dongyue.io`)
- 安卓组成员邮件列表
- 邮件的具体内容 (参考以前发给你的 Web 组周报)

**Comment by BrotherJing** [comment]
@arrowrowe  
发送地址：android-weekly@dongyue.io
接收地址：android-members@dongyue.io
成员邮箱：http://git.tongqu.me/dy/guide/blob/master/general/contact.md 里面所有android成员
核心成员：
cyy daniyuu@163.com
ljj 385858021@qq.com
我 brotherjing@sjtu.edu.cn

**Comment by BrotherJing** [comment]
补充

data binding
https://speakerdeck.com/jacobtabak/data-binding-techniques-at-droidcon-nyc-2015

RxJava介绍系列
http://www.devtf.cn/?p=382

MVP
https://medium.com/mobiwise-blog/android-basic-project-architecture-for-mvp-72f4b33252d0

facebook的android开源项目和文章
https://code.facebook.com/android/

**Comment by BrotherJing** [comment]
公共技术点之 View 绘制流程
http://a.codekk.com/detail/Android/lightSky/%E5%85%AC%E5%85%B1%E6%8A%80%E6%9C%AF%E7%82%B9%E4%B9%8B%20View%20%E7%BB%98%E5%88%B6%E6%B5%81%E7%A8%8B

creating custom view
http://code.tutsplus.com/tutorials/android-sdk-creating-custom-views--mobile-14548

**Comment by at15** [comment]
https://github.com/oasisfeng/nevolution 看上去很屌, 肥皂姐姐的男神star的... 不知道是干啥的

**Comment by arrowrowe** [comment]
@BrotherJing 这个 issue 是不是该关了? 已经发布到 [20151101](https://github.com/dyweb/android-stuff/blob/master/weekly/20151101.md) 了.

@at15 投到下一期吧

**Comment by at15** [comment]
@arrowrowe done. And I think I can close the issue for Jing
