### ISSUE TITLE
http://tongqu.me/index.php/api/doc/ 无法查看接口文档

### ISSUE THREAD

**Issue by gdshen** [dyweb/android-stuff#14]
http://tongqu.me/index.php/api/doc/ 返回{"version":"1.0","error":1,"msg":"\u4e0d\u5b58\u5728\u7684api","code":0}

**Comment by ComMouse** [comment]
？曾经有过文档么？@at15 @BrotherJing

**Comment by at15** [comment]
以前一直是看 git 里的 at15/doc 并没有生成的文档
