### ISSUE TITLE
Android weekly 1107

### ISSUE THREAD

**Issue by BrotherJing** [dyweb/android-stuff#2]

**Comment by BrotherJing** [comment]
http://drops.wooyun.org/papers/10061
转自web weekly

**Comment by at15** [comment]
伯乐在线的中文版 awesome-java https://github.com/jobbole/awesome-java-cn  
https://github.com/oasisfeng/nevolution 看上去很屌, 肥皂姐姐的男神star的... 不知道是干啥的

**Comment by BrotherJing** [comment]
http://chiuki.github.io/advanced-android-textview/#/
http://flavienlaurent.com/blog/2014/01/31/spans/
优化显示html，detail页面考虑使用

**Comment by BrotherJing** [comment]
Appbar, may replace our old actionbar
https://blog.stylingandroid.com/appbar-part-1/

more elegant layout in new sdk version
http://saulmm.github.io/mastering-coordinator/

android图表工具 在交汇里面有使用
https://github.com/PhilJay/MPAndroidChart

some libraries for rich text display
https://github.com/zzhoujay/RichText
https://github.com/klinker24/Android-TextView-LinkBuilder
https://github.com/chiuki/advanced-textview
