### ISSUE TITLE
weekly for 11-14

### ISSUE THREAD

**Issue by at15** [dyweb/android-stuff#3]
such a ... day

**Comment by at15** [comment]
https://github.com/tangqi92/BuildingBlocks 积木, 稍微改一改就可以变成一款新的应用。

**Comment by BrotherJing** [comment]
为何强行光棍。。我们每周六发的。。

**Comment by arrowrowe** [comment]
[蜻蜓FM涉嫌诈骗投资人和广告主源代码剖析](https://github.com/cryfish2015/QingTingCheat)

**Comment by at15** [comment]
https://github.com/wasabeef/richeditor-android 安卓上的富文本编辑器

**Comment by BrotherJing** [comment]
https://github.com/SeniorZhai/QingTing
上面那个被封了

**Comment by at15** [comment]
安卓热修复
- https://github.com/jasonross/Nuwa
- https://github.com/bunnyblue/DroidFix
