### ISSUE TITLE
20160102

### ISSUE THREAD

**Issue by BrotherJing** [dyweb/android-stuff#7]

**Comment by BrotherJing** [comment]
https://github.com/bboyfeiyu/android-tech-frontier/tree/master/androidweekly/%E9%82%A3%E4%BA%9B%E5%B9%B4%E6%88%91%E4%BB%AC%E9%94%99%E8%BF%87%E7%9A%84%E5%93%8D%E5%BA%94%E5%BC%8F%E7%BC%96%E7%A8%8B?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io
那些年我们错过的响应式编程

**Comment by BrotherJing** [comment]
http://gank.io/post/560e15be2dca930e00da1083
给 Android 开发者的 RxJava 详解

http://guides.codepath.com/android/Consuming-APIs-with-Retrofit
retrofit

**Comment by BrotherJing** [comment]
http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/1109/3662.html
retrofit 2 新特性

**Comment by at15** [comment]
@BrotherJing 怎么突然活跃了, 科创做完了?

**Comment by BrotherJing** [comment]
@at15 软工突然决定写android。。 顺便学一下酷炫框架

**Comment by at15** [comment]
@BrotherJing 点赞....

**Comment by at15** [comment]
- [安装包立减1M--微信Android资源混淆打包工具](http://mp.weixin.qq.com/s?__biz=MzAwNDY1ODY2OQ==&mid=208135658&idx=1&sn=ac9bd6b4927e9e82f9fa14e396183a8f#rd)

and @BrotherJing 已经1.7了, 不过web组的也跳票了....

**Comment by at15** [comment]
the mail is sent, so ...  btw: @arrowrowe is it possible to add a button to let other people subscribe & unsubscribe weekly

**Comment by arrowrowe** [comment]
re @at15: ......You mean the weekly email?...

**Comment by at15** [comment]
@arrowrowe yep ..... what's wrong, we only got a few strange content, most of them are trending repos ...
